C = float(input('Digite o valor dos graus em °C: '))
print('O valor de {}°C é o mesmo que {}°F.'.format(C,(C*9/5+32)))
F = float(input('Digite o valor em °F: '))
C1 = float(input((F-32)*5/9))
print('O valor de',F,'°F é igual a',C1,'°C')